route:
  receiver: 'slack-alerts'
receivers:
  - name: 'slack-alerts'
    slack_configs:

      - send_resolved: true
        api_url: ''
        channel: '#alerts'
        text: "ðŸ”¥ *Alert:* {{ .CommonAnnotations.summary }}\n{{ .CommonAnnotations.description }}"
